TIME & SPACE COMPLEXITY ADDED
ProAlgos/ProAlgos-Cpp pull request #10
Opened 2017-01-31 13:08 UTC by lelouch-lampourge

2017-01-31 13:30 UTC, faheel commented
The problem in Kadane's algorithm has already been fixed. See [Kadane.cpp](https://github.com/faheel/Algos/blob/master/MaximumSubarray/Kadane.cpp).

2017-01-31 13:33 UTC, faheel commented
The time complexity is O(N) and space complexity is O(1).

2017-01-31 13:35 UTC, lelouch-lampourge commented
but i have added the time and space complexity for binary search

2017-01-31 13:36 UTC, faheel requested changes
The space complexity is incorrect.

2017-01-31 13:36 UTC, faheel commented on Searching/BinarySearch.cpp
> +    SPACE COMPLEXITY :: O(log n) since in recursion we use stack.
The time complexity is `O(N)` and space complexity is `O(1)`.

2017-01-31 13:38 UTC, faheel requested changes
Write it in the format specified in #8.

2017-01-31 13:42 UTC, faheel commented
Space of internal stack for function calls isn't considered while calculating the space complexity.

2017-02-26 08:09 UTC, faheel commented
@lelouch-lampourge There are a few changes that I've mentioned in the review. Please take a look so that we can merge this as soon as possible.

2017-02-26 10:52 UTC, faheel requested changes
Your PR also contains the file for Kadane's algorithm, which is not required. Please remove that file.

2017-02-26 10:52 UTC, faheel commented on Searching/BinarySearch.cpp
> +    O(log n), where n is the number of elements in the array
Better write it as:
`O(log(N)), where N ...`

2017-03-12 10:45 UTC, faheel commented
Closing this since there hasn't been any activity for a long time.

2017-03-12 10:45 UTC, closed without merging