Adding matrix chain multiplication algo + unit test
ProAlgos/ProAlgos-Cpp pull request #105
Opened 2017-09-11 04:52 UTC by khushman1

Resolves Issue #87 

Adding the algorithm and associated unit test.
@faheel Please review

2017-09-26 19:29 UTC, faheel requested changes
Thank you for contributing! There are a few minor changes that need to be made and then it'll be good to merge.

2017-09-26 19:29 UTC, faheel commented on C++/README.md
> +  * [Matrix Chain Multiplication](source/dynamic_programming/matrix_multiplication.cpp)
Since you've also added the unit test, you can put a check mark (:white_check_mark:) after the link. The Markdown code for it is `:white_check_mark:`

2017-09-26 19:29 UTC, faheel commented on C++/source/dynamic_programming/matrix_multiplication.cpp
> +
It would make things clearer if this function is named `get_num_matrices`, asks the user to `"Enter the number of matrices : "`, and stores the value in a variable named `num_matrices`.

2017-09-26 19:29 UTC, faheel commented on C++/source/dynamic_programming/matrix_multiplication.cpp
> +    int size = values.size();
`size`, `chain_length`, `i`, `j`, `k` should all be of type `size_t`

2017-09-26 19:29 UTC, faheel commented on C++/source/dynamic_programming/matrix_multiplication.cpp
> +        cin >> val;
This function too should be renamed to something more appropriate like `get_matrix_orders` or something. The input prompt and the vector's name also need to be changed accordingly.

2017-09-28 07:53 UTC, khushman1 commented
@faheel Thanks for the comments. I've done them as requested.

2017-10-28 15:52 UTC, merged

2017-10-28 15:55 UTC, faheel commented
@khushman1 Thanks a lot for your contribution to the project! :smiley: