Added Edit Distance Algorithm in String Algorithms
ProAlgos/ProAlgos-Cpp pull request #130
Opened 2017-10-24 12:03 UTC by mayanktaluja

2017-11-04 10:39 UTC, faheel requested changes

2017-11-04 10:39 UTC, faheel commented on C++/source/string/edit_distance.cpp
> +#include<bits/stdc++.h>
It's good practice to only `#include` those headers that are required.

Also, this header is not present on OS X, as so the code does not compile on it.

2017-11-04 10:39 UTC, faheel commented on C++/source/string/edit_distance.cpp
> +}
No need for this function. You can instead use `min({some_val, some_other_val, yet_another_val})` in your code.

2017-11-04 10:39 UTC, faheel commented on C++/source/string/edit_distance.cpp
> +    string str2 = "saturday";
To make it more dynamic, please take the input for `str1` and `str2` from the user.

2017-11-04 10:39 UTC, faheel commented on C++/source/string/edit_distance.cpp
> +                    Where m = length of string1 and n = string2
The space complexity is O(1).

2018-08-30 15:36 UTC, alxmjo commented
Looks like this hasn't been updated in a few months. Closing.

2018-08-30 15:36 UTC, closed without merging