Ternary search
ProAlgos/ProAlgos-Cpp pull request #141
Opened 2017-11-18 14:26 UTC by qrort

Added ternary search implementation in C++.

2017-11-20 08:11 UTC, qrort commented
Hello. Sorry for unopened issue, I hope you are not against any new implementation :)
I wonder why not the .cpp gets the build error, but the new point in algos list, Could you help me figure this out? Thanks/

2017-11-20 13:21 UTC, faheel commented
> Sorry for unopened issue, I hope you are not against any new implementation :)

Not at all! 🙂  But it's always better to open an issue saying that you would like to contribute "algorithm X" or whatever and would be sending a PR for it, so that others know that someone is already working on "algorithm X". So please open an issue now for it.

> I wonder why not the .cpp gets the build error, but the new point in algos list

If you take a look at the Travis build log you'll see that it's the cpp file that causes the build to fail. The reason why the second commit is marked as "failed" is because [that's the way Travis works](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation).

2017-11-20 17:22 UTC, qrort commented
I am sorry, but I don't quite get it. What's the way I can figure out what's the problem in build on osx?

2017-11-20 21:05 UTC, faheel commented
Nothing seems to be wrong on your part. Something's wrong with Travis not being able to install a Python library. I'll look into it and get back to you.

2017-11-27 13:24 UTC, qrort commented
any upcoming info?

2017-11-28 00:07 UTC, qrort commented
Btw is there a method to merge small commits into one so they don't look like now? Or do I need to cancel them and make one?

2017-11-28 11:11 UTC, qrort commented
Now it is down to problems with Python again.

2017-11-29 18:52 UTC, faheel commented
> Btw is there a method to merge small commits into one so they don't look like now?

Yes, read about [squashing commits in Git](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

2017-11-29 19:58 UTC, faheel commented
I've made changes to the code that was causing the OSX builds to fail. Please update your branch with the new changes.

2017-11-30 19:23 UTC, faheel requested changes
Your indentation isn't uniform. Please change it to 4 spaces per level.

2017-11-30 19:23 UTC, faheel commented on C++/test/searching/ternary_search.test.cpp
> +}
You missed
```C++
#undef TERNARY_SEARCH_TEST
```

2017-12-03 10:01 UTC, qrort commented on C++/test/searching/ternary_search.test.cpp
> +}
done

2017-12-04 20:07 UTC, faheel approved these changes

2017-12-04 21:30 UTC, qrort commented
Shall I close the request now?

2017-12-04 21:52 UTC, faheel commented
No, I'll merge it in just a few minutes

2017-12-04 21:54 UTC, faheel commented
It'll be easier for me if you squash your commits.

2017-12-04 22:12 UTC, merged

2017-12-04 22:12 UTC, faheel commented
Thank you for your time and contribution @qrort! 😃