Add Sieve Of Eratosthenes to generate prime numbers upto given number,N.
ProAlgos/ProAlgos-Cpp pull request #17
Opened 2017-02-12 18:18 UTC by Rushyendher

Added C++ code to generate prime numbers for the given input value N.

2017-02-12 19:55 UTC, faheel requested changes
This is very good @Rushyendher. Thanks!

There are however a few changes to be made before I merge this.

2017-02-12 19:55 UTC, faheel commented on NumberTheory/SieveOfEratosthenes.cpp
> +	int N;
Use a better name for `N`, such as `prime_limit`.

2017-02-12 19:55 UTC, faheel commented on NumberTheory/SieveOfEratosthenes.cpp
> +void getInput(int &N)
Would be better to change this to:
```C++
void getPrimeLimit(int &prime_limit)
```

2017-02-12 19:55 UTC, faheel commented on NumberTheory/SieveOfEratosthenes.cpp
> +vector<int> sieveOfEratosthenes(int A) {
Change the signature to:
```C++
(const int &prime_limit)
```

2017-02-12 19:55 UTC, faheel commented on NumberTheory/SieveOfEratosthenes.cpp
> +*/
Also add the time and space complexity as mentioned in #8.

2017-02-13 01:17 UTC, Rushyendher commented
ok. Thank you

2017-02-13 01:36 UTC, Rushyendher commented
Made the requested changes.

2017-02-13 20:09 UTC, faheel approved these changes

2017-02-13 20:14 UTC, faheel commented
I did a few more changes and merged it in [this commit](../commit/850141d5ba9a9abfc6ad8382723b0836cea526a5). Thanks again @Rushyendher!

2017-02-13 20:14 UTC, closed without merging