Comb sort
ProAlgos/ProAlgos-Cpp pull request #186
Opened 2018-08-27 00:39 UTC by ColeSeverson

- [X] Read the [contribution guidelines][contrib-guidelines]
- [X] Added [unit tests][unit-tests] (or unit tests have already been added)
- [X] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

2018-09-07 05:45 UTC, faheel requested changes
@ColeSeverson Thank you for contributing! There are only a few minor things to fix and then it'll be good to merge:
* Re-indent code with 4 spaces per indent level.
* Add a single space between `if`, `for`, `while` etc. and the opening parenthesis `(`. This makes the code easier to read as these statements can be distinguished from function calls more easily.
* Drop the changes in `README.md` that were merged from `master`. It's not required.
* Add an entry for comb sort in the contents (in `C++/README.md`).

2018-09-07 05:45 UTC, faheel commented on C++/include/sorting/comb_sort.hpp
> +void comb_sort(vector<int>& input, const int order = 1, const bool to_show_state = true){
`to_show_state` should be `false` by default.

2018-09-07 05:45 UTC, faheel commented on C++/include/sorting/comb_sort.hpp
> +		gap = (gap / shrink_factor); //This should automatically floor bc it is an int
This is simpler:
```c++
gap /= shrink_factor;
```

2018-09-07 22:43 UTC, ColeSeverson commented
On 2018-09-06 22:45, Faheel Ahmad wrote:
> @FAHEEL requested changes on this pull request.
> 
> @ColeSeverson [1] Thank you for contributing! There are only a few
> minor things to fix and then it'll be good to merge:
> 
>  	* Re-indent code with 4 spaces per indent level.
>  	* Add a single space between if, for, while etc. and the opening
> parenthesis (. This makes the code easier to read as these statements
> can be distinguished from function calls more easily.
>  	* Drop the changes in README.md that were merged from master. It's
> not required.
> 
> -------------------------
> 
> In C++/include/sorting/comb_sort.hpp [2]:
> 
>> +    Time Complexity
> +    ---------------
> +    O(N^2), worst case where N is the number of elements
> +    O(N^2/2^p), average case where p is the number of increments and
> N is the number of elements
> +
> +    Space Complexity
> +    ----------------
> +    O(1)
> +*/
> +
> +#include <iostream>
> +#include <vector>
> +
> +#include "./utils.hpp"
> +
> +void comb_sort(vector<int>& input, const int order = 1, const bool
> to_show_state = true){
> 
> to_show_state should be false by default.
> -------------------------
> 
> In C++/include/sorting/comb_sort.hpp [3]:
> 
>> +    ----------------
> +    O(1)
> +*/
> +
> +#include <iostream>
> +#include <vector>
> +
> +#include "./utils.hpp"
> +
> +void comb_sort(vector<int>& input, const int order = 1, const bool
> to_show_state = true){
> +    unsigned int gap = input.size();
> +    double shrink_factor = 1.3; //suggested as the optimal size
> +    bool sorted = false;
> +
> +    while(!sorted){
> +        gap = (gap / shrink_factor); //This should automatically
> floor bc it is an int
> 
> This is simpler:
> 
> gap /= shrink_factor;
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or mute the
> thread [5]. [ { "@context": "http://schema.org", "@type":
> "EmailMessage", "potentialAction": { "@type": "ViewAction", "target":
> "https://github.com/faheel/Algos/pull/186#pullrequestreview-153208404",
> "url":
> "https://github.com/faheel/Algos/pull/186#pullrequestreview-153208404",
> "name": "View Pull Request" }, "description": "View this Pull Request
> on GitHub", "publisher": { "@type": "Organization", "name": "GitHub",
> "url": "https://github.com" } }, { "@type": "MessageCard", "@context":
> "http://schema.org/extensions", "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title":
> "@faheel requested changes on 186", "sections": [ { "text":
> "@ColeSeverson Thank you for contributing! There are only a few minor
> things to fix and then it'll be good to merge:\r\n* Re-indent code
> with 4 spaces per indent level.\r\n* Add a single space between `if`,
> `for`, `while` etc. and the opening parenthesis `(`. This makes the
> code easier to read as these statements can be distinguished from
> function calls more easily.\r\n* Drop the changes in `README.md` that
> were merged from `master`. It's not required.", "activityTitle":
> "**Faheel Ahmad**", "activityImage":
> "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
> "activitySubtitle": "@faheel", "facts": [ ] } ], "potentialAction": [
> { "targets": [ { "os": "default", "uri":
> "https://github.com/faheel/Algos/pull/186#pullrequestreview-153208404"
> } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name":
> "Unsubscribe", "@type": "HttpPOST", "target":
> "https://api.github.com", "body": "{\n\"commandName\":
> \"MuteNotification\",\n\"threadId\": 372511719\n}" } ], "themeColor":
> "26292E" } ]
> 
> Links:
> ------
> [1] https://github.com/ColeSeverson
> [2] https://github.com/faheel/Algos/pull/186#discussion_r215850781
> [3] https://github.com/faheel/Algos/pull/186#discussion_r215851612
> [4] 
> https://github.com/faheel/Algos/pull/186#pullrequestreview-153208404
> [5]
> https://github.com/notifications/unsubscribe-auth/Am0jT_1OLnI-ljQAV3kgvQcno32QX4Mfks5uYgfqgaJpZM4WNBPn
Implemented the fixes that you requested. It should be up to spec now.

2018-09-07 22:44 UTC, ColeSeverson commented
@faheel Implemented the spacing checks that you wanted added, as well as adding it to the README.md

2018-09-09 09:25 UTC, faheel commented on C++/include/sorting/comb_sort.hpp
> +		gap = (gap / shrink_factor); //This should automatically floor bc it is an int
This is still pending.

2018-09-09 09:25 UTC, faheel commented on C++/include/sorting/comb_sort.hpp
> +void comb_sort(vector<int>& input, const int order = 1, const bool to_show_state = true){
This is still pending.

2018-09-09 09:33 UTC, faheel requested changes
A few changes that were requested in the previous review weren't made:
* Add a single space between `if`, `for`, `while` etc. and the opening parenthesis `(`. This makes the code easier to read as these statements can be distinguished from function calls more easily.
* Move `comb_sort.hpp` under `C++/include/algorithm/sorting/`.

2018-09-09 09:33 UTC, faheel commented on C++/README.md
> +  * [Comb sort](source/include/sorting/comb_sort.hpp)
Please maintain alphabetical sorting in the list.

2018-09-09 09:33 UTC, faheel commented on C++/include/sorting/comb_sort.hpp
> +	A sorting algorithm desinged to improve upon bubble sort by by eliminating small values        that start near the end of the list.
Looks like a newline got deleted here.

2018-09-09 20:45 UTC, ColeSeverson commented
@faheel Ok, I moved Comb_sort.hpp to include/algorithms/sorting/ and added spacing around the parenthesis on conditionals and loops. Let me know if anything else needs changing!

2018-09-14 22:51 UTC, ColeSeverson commented
@faheel Fixed the order in the README.md

2018-10-09 00:47 UTC, ColeSeverson commented
@faheel All changes should be fixed

2019-10-21 21:54 UTC, alxmjo commented
Assuming the tests that are currently running pass, then this should be good to merge.

2019-10-22 00:29 UTC, merged