0-1 Knapsack
ProAlgos/ProAlgos-Cpp pull request #191
Opened 2018-09-05 18:27 UTC by heisenberg-2505

Implemented the 0-1 knapsack problem.

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [ ] Updated the [Contents][contents]

Closes #188 

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

2018-09-05 18:56 UTC, alxmjo requested changes
Looks good! Just requesting a few little changes here.

2018-09-05 18:56 UTC, alxmjo commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +using namespace std;
[Avoid `using namespace std`](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice). Instead, reference what you need specifically, as in: 

`using std::vector;`

2018-09-05 18:56 UTC, alxmjo commented on C++/test/algorithm/dynamic_programming/0_1_knapsack.cpp
> +using namespace std;
Avoid `using namespace std`.

2018-09-05 18:56 UTC, alxmjo commented on C++/test/algorithm/dynamic_programming/0_1_knapsack.cpp
> +TEST_CASE("Base Cases", "[knapsack]") {
Can you add a few more test cases?

2018-09-05 20:05 UTC, alxmjo requested changes
I'd also like @Faheel to have a look at this.

2018-09-05 20:05 UTC, alxmjo commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +//using namespace std;
If code isn't being used, remove it rather than just commenting it out.

2018-09-05 20:05 UTC, alxmjo commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +typedef long long ll;
Instead of ll for long long, use LL. ll is very difficult to distinguish from 11.

2018-09-06 15:46 UTC, alxmjo approved these changes

2018-09-06 15:46 UTC, alxmjo commented
Thanks for making those changes. Going to leave this up to @faheel to review and merge.

2018-09-08 21:50 UTC, alxmjo commented
@heisenberg-2505 While we're waiting for Faheel's review, would you like to update the [Contents](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/README.md)?

2018-09-09 15:35 UTC, faheel requested changes
Please also add an entry for 0-1 knapsack in the contents (in `C++/README.md).

2018-09-09 15:35 UTC, faheel commented on C++/test/algorithm/dynamic_programming/0_1_knapsack.cpp
> +
You can add
```c++
using std::vector;
```
to prevent writing prefixing `vector` with `std::` every time.

2018-09-09 15:35 UTC, faheel commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +  std :: vector <  std :: vector < LL > > K (numberOfItems + 1, std :: vector< LL > (capacity + 1));
* Having whitespace between `std` `::` `vector` `<` `LL` `>` etc. isn't recommended. The following is better:
  ```c++
  std::vector<std::vector<LL>> K(numberOfItems + 1, std::vector<LL>(capacity + 1));
  ```
  Same for the function's parameters.
* `K` isn't a very informative name. Something like `maximum` or `maxValue` would be better.

2018-09-09 15:35 UTC, faheel commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +#define KNAPSACK_HPP
`KNAPSACK_HPP` isn't very specific and might conflict with other knapsack implementations that would be added later, so please change it to `0_1_KNAPSACK_HPP`.

2018-09-09 16:16 UTC, heisenberg-2505 commented on C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
> +#define KNAPSACK_HPP
When using `0_1_KNAPSACK_HPP` it gives the following error `macro names must be identifiers` so using `KNAPSACK_0_1_HPP` instead.

2018-09-13 15:16 UTC, heisenberg-2505 commented
Can you review my pull request?

2018-09-13 17:46 UTC, faheel approved these changes

2018-09-13 17:49 UTC, merged

2018-09-13 17:50 UTC, faheel commented
@heisenberg-2505 Thank you for contributing! :+1: