Added HeapSort Algorithms
ProAlgos/ProAlgos-Cpp pull request #20
Opened 2017-02-15 18:22 UTC by Satch97

This takes a heap, implemented using an array(vector in this case) to take advantage of the fact that the index numbers correlate from parent to child by index to index/2.

Any suggestions are welcome.

2017-02-16 13:27 UTC, faheel requested changes
- Add the "description comment" with time and space complexities, as described in issue #8.
- Use consistent indentation of four spaces per level.
- Add a single space between `for`, `while`, `if` and the following `(`.

2017-02-16 13:27 UTC, faheel commented on Sorting/HeapSort.cpp
> +void heapsort(vector<int> &heap,int size, int order,bool showState){
Use `const` for arguments whose value is not going to change, like `const int size`, `const int order`, `const bool showState`.

2017-02-16 13:27 UTC, faheel commented on Sorting/HeapSort.cpp
> +  int temp,n = size;
Use a more meaningful name instead of `n`, such as `last` or something else.

2017-02-16 13:27 UTC, faheel commented on Sorting/HeapSort.cpp
> +    for(int x = (size/2)-1; x>=0;x--){ //Searches and reheaps all non-leaf node
Use a more meaningful name for `x`, and/or describe its purpose in the comments.

2017-03-03 19:48 UTC, Satch97 commented
Thanks for the feedback! I have made the requested changes. Please review.

2017-03-04 11:18 UTC, faheel requested changes
### Please compile and test your code before committing any changes!

2017-03-04 11:18 UTC, faheel commented on Sorting/HeapSort.cpp
> +        }
Remove the empty `else{}`

2017-03-04 11:18 UTC, faheel commented on Sorting/HeapSort.cpp
> +
`O(N log(N))` would be better than `O(nlog n)`

2017-03-04 11:18 UTC, faheel commented on Sorting/HeapSort.cpp
> +        }
Use `and` instead of `&&`.

Also, add more spaces, like:
```C++
if ((order * heap[child]) < (order * heap[child+1]) and (child+1 < size)) {
```

2017-03-04 11:18 UTC, faheel commented on Sorting/HeapSort.cpp
> +    }
You forgot to change `n` to `last` here. 

**Always compile and test your code before committing any changes.**

2017-03-04 11:18 UTC, faheel commented on Sorting/HeapSort.cpp
> +    for (int curr_node = (size/2)-1; curr_node>=0;curr_node--){
Add more space, like:
```C++
for (int curr_node = size/2 - 1; curr_node >= 0; curr_node--) {
```

2017-03-04 18:22 UTC, Satch97 commented
Thanks for the feedback. I have made the appropriate changes, debugged and tested the algorithm. Please review!

2017-03-19 12:17 UTC, Satch97 commented
Hey @faheel just thought I'd remind you to check my updates.

2017-03-19 13:03 UTC, faheel commented
I'm sorry to have missed your updates, even while reopening the issue!

I'll take a look and review it as soon as I can.

2017-03-19 13:34 UTC, faheel requested changes
The indentation is not consistent at many places.

Please use 4 spaces to indent by a level. (I suggest that you configure your code editor to emit 4 spaces when you press the tab key, by using **soft tabs** and setting the **tab width to 4**.)

2017-03-19 13:34 UTC, faheel commented on Sorting/HeapSort.cpp
> +
`n` should be uppercase.

2017-03-19 13:34 UTC, faheel commented on Sorting/HeapSort.cpp
> +   int child = (parent*2)+1, temp;
Change 
```C++
  int child = (parent*2)+1, temp;
```
to
```C++
  int child = parent*2 + 1;    // left child in the heap "tree" (right child is `child + 1`)
  int temp;
```

2017-03-19 13:34 UTC, faheel commented on Sorting/HeapSort.cpp
> +    getInputValues(values, size);
Add a newline between groups of statements that belong together.

Eg.
```C++
  size_t size;
  getInputSize(size);

  vector<int> values(size);
  getInputValues(values, size);

  int order;
  string orderText;
  getOrder(order, orderText);

  ...
```
This helps improve code readability. Also, please follow this not only in this section but also elsewhere.

2017-03-19 13:34 UTC, faheel commented on Sorting/HeapSort.cpp
> +        }
Add a single tab before starting a single-line comment, and add a single space before the first character in the comment.

Eg.
```C++
child++;   // child refers to the larger of the two children
           // (or smaller when sorting in descending order)
```

2017-03-19 13:34 UTC, faheel commented on Sorting/HeapSort.cpp
> +        last-=1;
`last--` would be better instead of `last-=1`

2017-03-19 15:18 UTC, Satch97 commented on Sorting/HeapSort.cpp
> +        }
Should I split them into two lines as you did here?

2017-03-19 19:32 UTC, faheel commented on Sorting/HeapSort.cpp
> +        }
Yes. Adding them on the same line would make the line too long.

You should try to make each line of code to have 80 characters at max (it is not a hard limit but is widely followed).

2017-03-21 02:45 UTC, Satch97 commented
Please review when possible.

2017-03-25 06:34 UTC, Satch97 commented
Are there any more changes to be made?

2017-03-28 18:01 UTC, faheel requested changes

2017-03-28 18:01 UTC, faheel commented on Sorting/HeapSort.cpp
> +
`temp` is unused. You can remove it.

2017-03-28 18:01 UTC, faheel commented on Sorting/HeapSort.cpp
> +	int temp;
`temp` is unused. You can remove it.

2017-03-28 18:01 UTC, faheel commented on Sorting/HeapSort.cpp
> +
Change `numbers` to `integers` to be more specific.

Also add more information on what heapsort basically is/does (keep it short though). Something like:

> Heapsort is a comparison-based sorting algorithm that divides its input into a sorted and an unsorted region, and iteratively shrinks the unsorted region by extracting the largest element and moving that to the sorted region. It uses the heap data structure (implemented as a vector here) to find the maximum.

2017-03-30 20:48 UTC, Satch97 commented on Sorting/HeapSort.cpp
> +	int temp;
true

2017-03-30 20:48 UTC, Satch97 commented on Sorting/HeapSort.cpp
> +
true

2017-03-30 20:52 UTC, Satch97 commented on Sorting/HeapSort.cpp
> +
Updated request. Please review when you get the chance @faheel

2017-04-13 15:53 UTC, merged

2017-04-13 16:02 UTC, faheel commented
@Satch97 Congratulations on your first PR merge! It took a lot of time (it doesn't generally take this long :sweat_smile:). I hope you may have learned a thing or two from it. Thanks a lot for your contribution and patience!