Migrate Kadane's Algorithm
ProAlgos/ProAlgos-Cpp pull request #222
Opened 2018-10-12 16:20 UTC by alxmjo

Create Kadane's Algorithm as header file.
Create unit test file.
Delete old Kadane's .cpp file.
Update README.

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

2018-10-14 15:29 UTC, faheel requested changes

2018-10-14 15:29 UTC, faheel commented on C++/include/algorithm/dynamic_programming/kadane.hpp
>  tuple<int, size_t, size_t> maximumSubarray(const vector<int> &values)
The function should be renamed to `maximum_subarray`. Also, we can have an alias for it named `kadane` like so:

```cpp
int f1(int x, int y) {
    // actual definition
    return x + y;
}

int f2(int x, int y) {
    // simple aliasing of f1 as f2
    return f1(x, y);
}
```
or,

```cpp
#define f2 f1   // f2 will now be replaced by f1, effectively acting as an alias

int f1(int x, int y) {
    return x + y;
}
```

2018-10-14 15:59 UTC, alxmjo commented
@faheel Done.

2018-11-24 11:07 UTC, faheel approved these changes

2018-11-24 11:08 UTC, merged