Doubly linked list
ProAlgos/ProAlgos-Cpp pull request #234
Opened 2018-10-30 15:46 UTC by korrat

Added an implementation of a doubly linked list

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [ ] Updated the [Contents][contents]

Closes #187

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

2018-11-05 13:58 UTC, alxmjo commented
Hi @Korrat. Thank you for your contribution. Please see the issues raised by the Codacy quality review above and update your code accordingly.

2019-07-05 07:43 UTC, korrat commented
Sorry, I dropped the ball on this. Is there anything I should do to get this merged?

2019-07-05 11:43 UTC, faheel commented
@korrat You need to move the header file to `include/data_structure/linked_list/doubly_linked_list.hpp` and the test file to `test/data_structure/linked_list/doubly_linked_list.cpp`. In the meanwhile, me an/or @alxmjo will review your code in detail.

2019-07-19 15:29 UTC, korrat commented
Is this waiting on anything I should do?

2019-07-19 17:16 UTC, alxmjo commented
Thanks for the reminder. I will check this out this weekend. In the meantime, can you correct the following spacing issue in your tests?

`REQUIRE( temp.length() == 0);` → `REQUIRE(temp.length() == 0);`

2019-07-20 21:43 UTC, alxmjo requested changes
Looks good! See inline comments for a few minor changes, and please update the contents (`C++/README.md`) to reflect the addition.

2019-07-20 21:43 UTC, alxmjo commented on C++/include/data_structure/linked_list/doubly_linked_list.hpp
> +        bool is_empty(void);
Please test this function.

2019-07-20 21:43 UTC, alxmjo commented on C++/include/data_structure/linked_list/doubly_linked_list.hpp
> +        void set_value(const T& other) {
Please test `set_value()`

2019-07-20 21:43 UTC, alxmjo commented on C++/test/data_structure/linked_list/doubly_linked_list.cpp
> +#include "data_structure/linked_list/doubly_linked_list.hpp"
Add test cases with negative numbers and numbers greater than 5.

2019-07-21 21:11 UTC, alxmjo requested changes
Thanks for the changes! Everything looks good to me. Just need to fix this one typo.

2019-07-21 21:11 UTC, alxmjo commented on C++/test/data_structure/linked_list/doubly_linked_list.cpp
> +TEST_CASE("Inserting arbitray values", "[doubly-linked-list]") {
"arbitray" → "arbitrary"

2019-07-23 14:00 UTC, alxmjo approved these changes
These look good to me. I'll wait a day or so to merge in case @faheel wants to take a look, too. After that I'll go ahead and merge. Thank you for contributing!

2019-07-25 15:33 UTC, merged