Update C++/include/data_structures/doubly_linked_list.cpp
ProAlgos/ProAlgos-Cpp pull request #235
Opened 2018-11-05 06:43 UTC by Rda99

I added one of the most important topics of Data Structure, Doubly Linked List. Hope my first contribution is helpful.

2019-06-02 21:34 UTC, faheel requested changes
@Rda99 Sorry for the late review. If you're still interested in contributing this implementation then here are a few changes I suggest you make:

* Convert `doubly_linked_list.cpp` into a header file (`doubly_linked_list.hpp`) and remove `main()` from it.
* Drop the commits from the `master` branch.
* Add unit tests in `C++/test/data_structures/doubly_linked_list.cpp` (see [UNIT_TEST.md](https://github.com/faheel/Algos/blob/reorganise/C%2B%2B/UNIT_TESTS.md) for more details).

More changes in the comments below.

2019-06-02 21:34 UTC, faheel commented on C++/include/data_structures/doubly_linked_list.cpp
> +    double_llist dl;
The `main` function wouldn't be required as this would be a header file.

2019-06-02 21:34 UTC, faheel commented on C++/include/data_structures/doubly_linked_list.cpp
> +class double_llist
The class should be named `DoublyLinkedList`.

2019-06-02 21:34 UTC, faheel commented on C++/include/data_structures/doubly_linked_list.cpp
> +}*start;
`*start` should be a private class variable that is initialized in its constructor.

2019-07-25 16:58 UTC, alxmjo commented
@Rda99 Thanks for your work on this, Raj. Closing since we merged doubly linked list in #234.

2019-07-25 16:58 UTC, closed without merging