Migrate sorting algorithms
ProAlgos/ProAlgos-Cpp pull request #251
Opened 2019-06-08 22:49 UTC by alxmjo

I've moved over the rest of the sorting algorithms. The only anomaly (intentional anomaly, anyway) is that radix sort only sorts on positive integers, so I've left off the unit tests for now. I can add an issue to update the algorithm (using something [like this](https://stackoverflow.com/questions/15306665/radix-sort-for-negative-integers)).

2019-06-11 21:27 UTC, merged

2019-06-12 11:13 UTC, faheel requested changes

2019-06-12 11:13 UTC, faheel commented on C++/include/algorithm/sorting/radix_sort.hpp
> +int max_in_vect(const vector<int>& values) {
The function name should be `max_in_vector` (as in the comment).

2019-06-12 11:13 UTC, faheel commented on C++/include/algorithm/sorting/radix_sort.hpp
> +void radix_sort() {
Missing parameters in the function signature: `values`, `order`, and `to_show_state`.

2019-06-12 11:13 UTC, faheel commented on C++/include/algorithm/sorting/shell_sort.hpp
> +	int n = values.size();
The following would be better:
```cpp
size_t size = values.size();
```

2019-06-12 11:13 UTC, faheel commented on C++/include/algorithm/sorting/shell_sort.hpp
> +	for (int gap = n / 2; gap > 0; gap /= 2) {
* Type of `i`, `j` and `gap` should be `size_t`.
* `i` and `j` can be declared in their respective for loop's init statement. It's good practice to limit the scope of variables. On the same note, `temp` can also be declared inside the i-loop's body.

2019-06-12 11:13 UTC, faheel commented on C++/include/algorithm/sorting/merge_sort.hpp
> +void merge_sort_internal(vector<int>& values, const size_t start, const size_t end,
`merge_sort_internal` can be renamed to `merge_sort_range`, to signify that it's not just an internal function as it could be useful in scenarios where only a certain range of values in a vector need to be sorted.

2019-06-12 11:20 UTC, faheel commented
@alxmjo I had added some review comments yesterday but had forgotten to submit the review, and when I saw the open tab in my browser right now and finally submitted, only then did I see that the changes have already been merged.

I'll create a new issue to fix these changes later on.

2019-06-12 12:43 UTC, alxmjo commented
OK. I'm almost done migrating the remaining data structures. I can make these changes when I'm done with that.

2019-06-14 22:34 UTC, alxmjo commented on C++/include/algorithm/sorting/radix_sort.hpp
> +int max_in_vect(const vector<int>& values) {
Fixed in #253.

2019-06-14 22:34 UTC, alxmjo commented on C++/include/algorithm/sorting/shell_sort.hpp
> +	int n = values.size();
Fixed in #253.

2019-06-14 22:34 UTC, alxmjo commented on C++/include/algorithm/sorting/shell_sort.hpp
> +	for (int gap = n / 2; gap > 0; gap /= 2) {
Fixed in #253.

2019-06-14 22:34 UTC, alxmjo commented on C++/include/algorithm/sorting/merge_sort.hpp
> +void merge_sort_internal(vector<int>& values, const size_t start, const size_t end,
Fixed in #253.

2019-06-14 22:35 UTC, alxmjo commented
These fixes are implemented in #253.