Overloading  ternary search to accept a function and an interval as parameters
ProAlgos/ProAlgos-Cpp pull request #264
Opened 2019-09-03 01:28 UTC by sylvaus

Overloading ternary search to accept a function and an interval as parameters

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

Closes #261

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

2019-09-05 17:26 UTC, alxmjo commented
Thanks for contributing @sylvaus. Sorry I haven't had a chance to review it yet but I will soon!

2019-09-20 00:46 UTC, sylvaus commented
My pleasure

2020-05-28 00:01 UTC, alxmjo requested changes
Thank you for this contribution. Sorry it took me so long to look it over.

In addition to the inline notes I've made, I think it would be valuable to add comments on the general ideas of what the code is doing, both in the implementation and the tests. You don't need to comment every single line, but have a look at some of the other algorithms for an idea for what to aim for.

Finally, I'll also note that there are some changes we could make in the unit test for ternary, but it doesn't make sense to hold up this PR for pre-existing issues so we identify those in a separate issue/PR.

2020-05-28 00:01 UTC, alxmjo commented on C++/test/algorithm/searching/ternary_search.cpp
>  #include <algorithm>
I don't think `algorithm` is necessary here.

2020-05-28 00:01 UTC, alxmjo commented on C++/test/algorithm/searching/ternary_search.cpp
> +#include <math.h>
Use `cmath` instead.

2020-05-28 01:26 UTC, sylvaus commented
No problem, rework after review done

2020-05-28 16:52 UTC, merged