Fix broken links in README.md
ProAlgos/ProAlgos-Cpp pull request #338
Opened 2020-05-28 02:59 UTC by a-moreira

Fixed broken links in README.md

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

Closes #334 

Also updates README.md for Pull Request #337 

[contrib-guidelines]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md
[unit-tests]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/C++/CONTRIBUTING.md#unit-tests
[contents]: https://github.com/ProAlgos/ProAlgos-Cpp/tree/master/C%2B%2B#contents

2020-05-28 18:03 UTC, alxmjo requested changes
This looks great. Thank you. See my only comment about migrating the listing for Heap's.

2020-05-28 18:03 UTC, alxmjo commented on C++/README.md
> +  * [Heap's Algorithm](include/algorithm/string/heaps_algorithm.hpp) :white_check_mark:
Move this change into #337.

2020-05-30 00:18 UTC, alxmjo commented
This branch now has merge conflicts since Heap's was also added to readme in #337. Please resolve.

2020-05-30 00:27 UTC, a-moreira commented
I think everything is set up now

2020-05-30 00:41 UTC, alxmjo approved these changes

2020-05-30 00:41 UTC, alxmjo commented
Thanks!

2020-05-30 00:41 UTC, merged