Added code for fast fibonacci using Golden Ratio and Fast Exponentiation
ProAlgos/ProAlgos-Cpp pull request #365
Opened 2020-08-06 06:09 UTC by vs666

- [ ] Read the [contribution guidelines][contrib-guidelines]
- [ ] Added [unit tests][unit-tests] (or unit tests have already been added)
- [ ] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md
[unit-tests]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md#adding-unit-tests
[contents]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/README.md#contents

2020-08-06 16:19 UTC, alxmjo commented
Thanks for your contribution, @vs666. Looks like the build is failing. Please fix that and then I'll move forward with the review.

2020-08-06 16:40 UTC, alxmjo commented
And for what it's worth, I'd prefer a name besides `fibonacci_fast`. I'm not sure what a better name would be, but I think we should be specific about the strategy used (`fibonacci_golden`?) rather than just that it's "fast." Perhaps there's a clue somewhere in [here](https://en.wikipedia.org/wiki/Fibonacci_number#Binet's_formula).

2020-08-06 18:19 UTC, vs666 commented
@alxmjo I am unable to understand why my build is failing. I am relatively new, and could really use your advice.

2020-08-07 10:30 UTC, vs666 commented
@alxmjo build has passed, kindly review it.

2020-08-07 16:34 UTC, alxmjo commented
Thank you. I'll have a look soon. In the meantime please update the [Contents](https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/README.md#contents).

2020-08-10 17:29 UTC, vs666 commented
@alxmjo Contents have been updated. You can review the PR now.

2020-08-27 16:40 UTC, vs666 commented
@alxmjo any updates?

2020-09-13 17:40 UTC, alxmjo requested changes
Sorry it's taken me so long to get to this. Just a few minor requests regarding syntax and identifiers. Let me know if you have questions.

2020-09-13 17:40 UTC, alxmjo commented on README.md
> +    * [Golden Ratio (faster logarithmic time) algorithm](cpp/include/algorithm/number_theory/fibonacci_golden.hpp) :white_check_mark:
"Golden ratio algorithm". I don't think mentioning the timing is necessary.

2020-09-13 17:40 UTC, alxmjo commented on cpp/CMakeLists.txt
> +# Fast fibonacci using golden ratio
"Fast" is relative. I think just "Fibonacci using golden ratio" is better.

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    Fibonacci number
For consistency, "Fibonacci using golden ratio"

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    -----------------
Make sure hyphens match text above.

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    is f_(n+1) = f_(n)*(phi) where phi is golden ratio
Add period.

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +#endif // FIBONACCI_FAST_HPP
Change to match name of file.

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +long double ___modExp_____(const int ex) // Name is unconventional to prevent accidental clash with a function name in implementing class
Can you expand on this? Why are the underscores necessary?

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    int n=ex, exp=ex;
Add spaces between identifiers.

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    if (n%2==0) {
`if (n % 2 == 0)`...

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +        return sqrt(0.2)*(ans-1/(ans));
`return sqrt(0.2) * (ans - 1 / (ans));`

2020-09-13 17:40 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +        return sqrt(0.2)*(ans-1/(ans));
Fix other lines too, please.

2020-09-13 17:40 UTC, alxmjo commented on cpp/test/algorithm/number_theory/fibonacci_golden.cpp
> +TEST_CASE("Overflow cases", "[fibonacci]") {
Thanks for adding these.

2020-09-13 17:42 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +long double ___modExp_____(const int ex) // Name is unconventional to prevent accidental clash with a function name in implementing class
Please add a comment explaining what this function does and how it works. Also, I'd see if you can come up with a more descriptive identifier than `modExp`.

2020-09-13 17:42 UTC, alxmjo commented on cpp/include/algorithm/number_theory/fibonacci_golden.hpp
> +    while (exp)
In-line comments would be helpful here, too.

2020-12-01 07:08 UTC, closed without merging