GraphTheory added with Djikstra O(nlogn) implementation
ProAlgos/ProAlgos-Cpp pull request #37
Opened 2017-03-22 23:42 UTC by CoderINusE

2017-03-23 03:53 UTC, varunjm commented on GraphTheory/Dijkstra.cpp
> +    const int INF = 1000000; // initially all distances are equal infinity
Using INT_MAX  from the <climits> header is a better way to do this.

2017-03-23 08:21 UTC, CoderINusE commented on GraphTheory/Dijkstra.cpp
> +    const int INF = 1000000; // initially all distances are equal infinity
Ok, but not the INT_MAX but INT_INF.

2017-03-23 12:33 UTC, faheel requested changes

2017-03-23 12:33 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +#define INF 2147483647
A better way is
```C++
const int INF = INT_MAX;
```

2017-03-23 12:33 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +
- typedef `vector<vector<pair<int, int>>>` to `Graph`,
- Rename `g` to `graph`,
- Make `graph`, `vertices` and `edges` as local variables of `main()`. You can pass the graph as a constant reference (`const Graph& graph`) to `dijkstra()`.

2017-03-23 12:33 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +	vector<int> d = dijkstra(1);
Rename `d` to `distances` or `min_distances`

2017-03-23 12:33 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +}
Missing `return` statement

2017-03-23 12:33 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +
Add the "description comment" at the very top as mentioned [here](../blob/master/CONTRIBUTING.md#general-guidelines).

2017-03-23 12:51 UTC, CoderINusE commented on GraphTheory/Dijkstra.cpp
> +
Done.

2017-03-23 13:20 UTC, faheel requested changes
- Use consistent indentation of four spaces per level
- Add a single space between `for`, `while`, `if` and the following `(`
- Rename to folder to just `Graph`

2017-03-23 13:20 UTC, faheel commented on GraphTheory/Dijkstra.cpp
> +vector<int> dijkstra(const int &start, const Graph& graph, const int& vertices, const int& edges) {
There's no need to have `vertices` and `edges` as arguments

2017-03-23 13:20 UTC, faheel commented on GraphTheory/Dijkstra.cpp
>  	cout << "Now enter your edges in format: \"u v w\". Where u and w are vertices and w is the distance between them." << endl;
The following will be more comprehensible:
```C++
cout << "Enter the edges in the format:" << "\n";
cout << "a w b" << "\n";
cout << "where \'a\' and \'b\' are vertices, and \'w\' is the distance between them." << "\n";
```

2017-03-23 13:50 UTC, faheel commented
In case you missed them, other changes are still pending. Please read the review above.

2017-03-23 14:06 UTC, CoderINusE commented
Anything else?

2018-01-10 17:57 UTC, faheel commented
Sorry for not reviewing your PR back then. The project has been updated quite a lot, so if you're still interested in getting this PR merged, feel free to re-open it and add a comment stating that you are, and I'll help you in making the required changes. Sorry once again for replying so late, and thanks a lot for taking the time to contribute to the project.

2018-01-10 17:57 UTC, closed without merging