Add Binary Search Tree
ProAlgos/ProAlgos-Cpp pull request #38
Opened 2017-03-23 01:31 UTC by varunjm

- Adds binary search tree under a new 'Trees' folder.
- Includes insert, remove, Inorder traversal, Preorder traversal, Postorder traversal. Both iterative and recursive.
- Has the time and space complexities where ever applicable

2017-03-23 12:09 UTC, faheel requested changes
I think it would be better to declare the BST as a class (named `BinarySearchTree`), having:
- Data members:
  - `root` of type `Node*`
- Member functions:
  - a constructor for initialising the `root` node
  - `insert_node()`
  - `remove_node()`
  - `traverse_inorder()`
  - `traverse_preorder()`
  - `traverse_postorder()`

Also, it would be better to separate the declarations into a header file called `BinarySearchTree.hpp` and the definitions for them in `BinarySearchTree.cpp`

2017-03-23 12:09 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +    struct treeNode * rightChild;
A node can be defined more simply like:
```C++
struct Node {
    int value;
    Node* left_child;
    Node* right_child;
};
```

2017-03-23 12:09 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +    newNode->leftChild = newNode->rightChild = NULL;
Use [`nullptr`](http://en.cppreference.com/w/cpp/language/nullptr) instead of `NULL` for a null pointer.

2017-03-23 12:09 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +
Also initialise the left and right children of `newNode` as `nullptr`

2017-03-23 14:08 UTC, varunjm commented on Trees/BinarySearchTree.cpp
> +
getNode() initialized all new node with left and right children as null

2017-03-25 02:43 UTC, varunjm commented
@faheel The requested changes have been made.

2017-03-28 18:52 UTC, faheel requested changes
- Don't put spaces around `::`
- Avoid declaring multiple pointers in the same declaration
- Use `and ` instead of `&&`, and `or` instead of `||`
- Declare pointers as `type* name;`

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.hpp
> +};
There's no need to write `struct` when declaring an object of a structure in C++.

Therefore, change the last 2 lines to:
```C++
    Node* left_child;
    Node* right_child;
```

Also note that you should **not declare pointers like `type * name`!** Instead, you should either write `type* name` or `type *name`, though `type* name` is the preferred choice of most programmers. (Don't forget to make this change in other places as well.)

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +    root->value = INT_MAX;
Instead of assigning `INT_MAX` directly, declare a global constant integer named `INF`, set it to `INT_MAX` and use that in place of `INT_MAX`.

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +bool BinarySearchTree :: insert_node(int value) {
Don't put spaces around `::`

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +        Node * iter = root, * newNode = get_node();
Avoid declaring multiple pointers in the same declaration. [See details](https://google.github.io/styleguide/cppguide.html#Pointer_and_Reference_Expressions).

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +    Node * iter;
Rename `iter` to `current` or `current_node`.

2017-03-28 18:52 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +                if (iter->right_child == nullptr && iter->left_child == nullptr) {
Use `and ` instead of `&&`, and `or` instead of `||`

2017-04-04 10:08 UTC, faheel commented
I just realised that traversal of a data structure isn't a part of. It's just an algorithm that is applied to a data structure to access it's elements.

I therefore think that all the traversal algorithms should be implemented separately in the `Tree/BinarySearchTree/Traversal` folder, and the rest of the code for BST should be added to the `DataStructures/Trees/BinarySearchTree` folder.

Do comment and let me know your view on this.

2017-04-06 13:34 UTC, varunjm commented
I had thought about it before my PR, but I decided against it.

1. It would lead to a very confusing arrangement for any beginner who is looking to understand the working from this code.
2. In-order, pre-order and post-order traversals are almost always associated with Binary search trees.

2017-04-13 11:53 UTC, faheel requested changes

2017-04-13 11:53 UTC, faheel commented on Trees/BinarySearchTree.hpp
> +    void traversal_postorder_helper(Node* tree);
I don't think there's a need for these 3 functions. They can be removed (from the _cpp_ file as well)

2017-04-13 11:53 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +
To declare constants, use a `const` "variable", rather than the `#define` directive.
```C++
const int INF = INT_MAX;
```

2017-04-19 05:00 UTC, varunjm commented on Trees/BinarySearchTree.hpp
> +    void traversal_postorder_helper(Node* tree);
It is a recursive function with the current node being passed as an argument. The function call to the traversal methods using objects makes it unnecessary and not possible to pass the current node as an argument to it. This is needed.

2017-04-19 05:02 UTC, varunjm commented on Trees/BinarySearchTree.cpp
> +
INT_MAX max is (sort of) a constant declared in the "climits" library. Why should i redeclare it as a constant? The only reason I have this line is to rename the constant to be more meaningful.

2017-04-29 18:52 UTC, varunjm commented
Any views on my comments?

2017-04-30 07:38 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +
By using a `const` you would be doing the same thing that you are doing with `#define` - giving the constant a better name, but in a more standard way for C++ (`#define` is old C style, modern C has `const` for the same purpose).

2017-04-30 10:29 UTC, faheel requested changes

2017-04-30 10:29 UTC, faheel commented on Trees/BinarySearchTree.hpp
> +    void traversal_inorder_recursive();
The **search** operation is missing, which is the one of the most important operation in a BST. Can you please add it?

2017-04-30 10:29 UTC, faheel commented on Trees/BinarySearchTree.hpp
> +    void traversal_postorder_helper(Node* tree);
If you set the default value of the argument of the recursive functions as `root` (the tree's root), then the helper functions can be removed and the functions can still be called from `main()` (or other external functions) without passing an argument - the way they are called now.

Eg.
```C++
void BinarySearchTree::traverse_inorder_recursive(Node* node = root) {
    if (node == nullptr or node->value == INF)
        return;

    traverse_inorder_recursive(node->left_child);
    std::cout << node->value << '\n';
    traverse_inorder_recursive(node->right_child);
}
```

2017-04-30 10:29 UTC, faheel commented on Trees/BinarySearchTree.hpp
> +    bool remove_node(int);
I suggest that you rename `insert_node` and `remove_node` to `insert` and `delete` respectively, which are the more conventional names for the operations, followed in many other places including the STL.

2017-04-30 10:29 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +    Best case : O(log n), where n is the number of nodes in the tree
_O_(log(N))  is the average case. Best case will be _O_(1), so there's no need to mention it. Mention the average case instead, along with the worst case (for other methods too).

2017-04-30 10:29 UTC, faheel commented on Trees/BinarySearchTree.cpp
> +        return false;
Simplify this function by breaking the different operations that happen in it (like finding the successor etc.) into separate functions, and call those functions here.

2017-05-30 16:33 UTC, varunjm commented on Trees/BinarySearchTree.cpp
> +
Okay, I'll change it.

2017-05-30 16:34 UTC, varunjm commented on Trees/BinarySearchTree.hpp
> +    bool remove_node(int);
Okay.

2017-05-30 16:34 UTC, varunjm commented on Trees/BinarySearchTree.hpp
> +    void traversal_inorder_recursive();
Sure.

2017-05-30 16:36 UTC, varunjm commented on Trees/BinarySearchTree.cpp
> +    Best case : O(log n), where n is the number of nodes in the tree
My bad. Will update this.

2017-05-31 11:51 UTC, varunjm commented on Trees/BinarySearchTree.hpp
> +    void traversal_postorder_helper(Node* tree);
This is disallowed in C++. The best I can do is overload the same function name instead of naming it a 'helper'.

2017-06-22 14:50 UTC, varunjm commented
@faheel Any more changes?

2017-06-23 05:40 UTC, faheel commented
@varunjm I've troubled you enough :smile:. It's time to merge!

2017-06-23 05:41 UTC, merged

2017-06-23 05:42 UTC, faheel commented
Thanks a lot for your contribution and patience! :smiley:

2017-06-27 12:01 UTC, varunjm commented
@faheel I dont mind it at all. Great working with you.

2017-06-27 12:44 UTC, Shabalang commented
This will also hekp me. I am open to criticism. Please let me know of any possible improvments i can implement


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Varun Jayathirtha <notifications@github.com> Date: 6/27/17  7:01 AM  (GMT-06:00) To: faheel/Algos <Algos@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [faheel/Algos] Add Binary Search Tree (#38) 
@faheel I dont mind it at all. Great working with you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/faheel/Algos","title":"faheel/Algos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/faheel/Algos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@varunjm in #38: @faheel I dont mind it at all. Great working with you. "}],"action":{"name":"View Pull Request","url":"https://github.com/faheel/Algos/pull/38#issuecomment-311337399"}}}