Sorting Algos' Description Update
ProAlgos/ProAlgos-Cpp pull request #45
Opened 2017-04-16 22:42 UTC by abhishekabk5

2017-04-18 18:49 UTC, faheel requested changes
I don't think there's a need to mention `temporary space for swapping` where the space complexity is _O(1)_.

2017-04-18 18:49 UTC, faheel commented on Sorting/QuickSort.cpp
> +    Average case: O(N * log(N)).
```
Expected worst case: O(N * log(N)),
Absolute worst case: O(N^2),
where N is the number of elements.
```

2017-04-18 18:49 UTC, faheel commented on Sorting/QuickSort.cpp
> +    calls itself on those partitions and then merges them after sorting.
Quick sort doesn't "merge" the partitions.

The description should therefore be like: `It randomly picks an element as pivot, partitions the given array around the selected pivot while placing the pivot in its sorted position, and recursively calls itself on those partitions.`

2017-04-18 18:49 UTC, faheel commented on Sorting/MergeSort.cpp
> + /*
Extra space spotted!

2017-04-18 18:49 UTC, faheel commented on Sorting/MergeSort.cpp
> +    O(N), temporary space for array used in merging.
```
O(N), where N is the number of elements.
This space is used for merging two halves of the array.
```

2017-04-20 15:51 UTC, abhishekabk5 commented
I hope the changes are up to mark now.
I apologise for any inconvenience caused, I am new to open source. :)

2017-04-21 15:47 UTC, faheel requested changes

2017-04-21 15:47 UTC, faheel commented on Sorting/QuickSort.cpp
> +    Where N is the number of elements.
All `W`s in lower-case.

2017-04-21 15:53 UTC, faheel commented
@abhishekabk5 No inconvenience caused :smile:. Keep learning!

2017-04-21 15:57 UTC, faheel commented on Sorting/QuickSort.cpp
> +    calls itself on those partitions.
It randomly picks an element as pivot, partitions the given array around the selected pivot while placing it in its proper position, and recursively calls itself on those partitions.

2017-04-21 15:59 UTC, faheel commented on Sorting/InsertionSort.cpp
> +    one item at a time. Less suitable for larger lists.
`larger` -> `large`

2017-04-21 16:23 UTC, faheel commented on Sorting/MergeSort.cpp
> +    then merges the two sorted halves.
```
An efficient, comparison-based, divide and conquer sorting algorithm.
It divides the input array into two halves, recursively calls itself for those halves, and then merges
the two sorted halves back.
```

2017-04-21 16:29 UTC, faheel commented on Sorting/SelectionSort.cpp
> +    part and putting it at its right place.
```
A simple in-place comparison-based sorting algorithm.
It sorts an array by finding the smallest / largest element (depending on the sorting order)
in the unsorted sublist, swapping it with the leftmost unsorted element, and moving the sublist
boundaries one element to the right.
```

2017-04-21 16:49 UTC, faheel requested changes
Here are my final thoughts on the descriptions.

**NOTE**: Put a line break after the first sentence and make sure each line is at most 100 characters.

2017-04-23 21:45 UTC, faheel requested changes

2017-04-23 21:45 UTC, faheel commented on Sorting/InsertionSort.cpp
> +        /*
One last thing (extra tab) :sweat_smile:

2017-04-25 03:27 UTC, faheel approved these changes

2017-04-25 08:30 UTC, merged

2017-04-25 08:32 UTC, faheel commented
@abhishekabk5 Thanks for your time and contribution, and congratulations on your first PR merge! :smiley::+1: