Add shell sort algorithm.
ProAlgos/ProAlgos-Cpp pull request #52
Opened 2017-05-06 09:29 UTC by Hossam-Tarek

2017-05-06 12:32 UTC, Hossam-Tarek commented
Modify format of the file there was a problem with the tab size

2017-05-09 10:09 UTC, faheel requested changes
Please make use of the utility functions in [SortingUtils.hpp](../blob/master/Sorting/SortingUtils.hpp). You can take help from other [sorting programs](../blob/master/Sorting) to see how and where to use these functions.

2017-05-09 10:09 UTC, faheel commented on Sorting/ShellSort.cpp
> +    by calculating a gap sequence (gap = n / 2)
A few grammatical errors here, like
- `we starts` -> `we start`
- `that are less far apart` -> `that are much closer`
- `and finally comparing adjacent elements.` -> `and then finally compare adjacent elements, `

2017-05-09 10:09 UTC, faheel commented on Sorting/ShellSort.cpp
> +    by calculating a gap sequence (gap = n / 2)
The following description would be better in my opinion:
> `An in-place comparison sort which starts by sorting pairs of elements far apart from each other, then progressively reducing the gap between elements to be compared. The time complexity depends on the gap sequence, which is floor(N/2^k) in this implementation.`

2017-05-09 10:09 UTC, faheel commented on Sorting/ShellSort.cpp
> +    O(N*log(N)^2), where N is the nubmer of elements.
For the gap sequence used, the time complexity is O(N^2).

2017-05-09 13:09 UTC, Hossam-Tarek commented
please review this implementation now @faheel

2017-05-09 16:54 UTC, faheel requested changes
A few more changes are required before this can be merged.

2017-05-09 16:54 UTC, faheel commented on Sorting/ShellSort.cpp
> +        cout << arr[i] << " ";
This can now be removed.

2017-05-09 16:54 UTC, faheel commented on Sorting/ShellSort.cpp
> +            for (j = i; j >= gap && values[j - gap] > temp; j -= gap)
Use `and` and `or` instead of `&&` and `||` respectively.

2017-05-09 16:54 UTC, faheel commented on Sorting/ShellSort.cpp
> +            int j;
Declare the variables `temp`, `i` and `j` outside the loops to prevent redeclaration on every iteration.

2017-05-09 16:54 UTC, faheel commented on Sorting/ShellSort.cpp
> +}
`return 0;` is missing at the end.

2017-05-09 18:00 UTC, Hossam-Tarek commented
what about now?
and do you have any reason of putting 'return 0' the compiler without it works fine.

2017-05-09 18:29 UTC, faheel commented
@Hossam-Tarek, looks good now! 👍 

And about `return 0;`, it is required, by standard, at the end of `main()` because the return code signals the OS that the program has exited successfully (`0` is success, non-0 is failure). This helps in debugging a software where lots of programs are involved, and their exit status may be checked to know whether or not a program executed successfully. If you don't write it, the program will return some random value, which is not helpful in any way.

2017-05-09 18:30 UTC, merged

2017-05-09 19:10 UTC, Hossam-Tarek commented
@faheel thank you for your help
this was my first contribution in GitHub

2017-05-09 22:07 UTC, faheel commented
Happy to help :smiley: . And congratulations on your first PR merge! :tada: