Adding Graph
ProAlgos/ProAlgos-Cpp pull request #61
Opened 2017-06-04 11:18 UTC by deathcod

Below are BFS and DFS, more to come

2017-07-28 18:22 UTC, ryoung9550 requested changes

2017-07-28 18:22 UTC, ryoung9550 commented on DataStructures/Graph/BreadthFirstSearch.cpp
> +int main() {
This test function should be renamed a different name then called by the main test.cpp

2017-07-28 18:22 UTC, ryoung9550 commented on DataStructures/Graph/DepthFirstSearch.cpp
> +int main() {
Same as the DFS cpp file, the function should be named something else so it can be tested. This would create multiple entry points when compiling.

2018-01-10 18:04 UTC, faheel commented
Sorry for not reviewing your PR back then. The project has been updated quite a lot, so if you're still interested in getting this PR merged, feel free to re-open it and add a comment stating that you are, and I'll help you in making the required changes. Sorry once again for replying so late, and thanks a lot for taking the time to contribute to the project.

2018-01-10 18:04 UTC, closed without merging