Add BinomialCoeffcients.cpp
ProAlgos/ProAlgos-Cpp pull request #66
Opened 2017-06-08 16:11 UTC by eskeype

This program computes (N choose K) using a recurrence relation and dynamic programming. I think that this program would be a good addition as it showcases basic dynamic programming, and because I feel as though dynamic programming implementations of this algorithm are hard to find.

2017-06-09 02:36 UTC, faheel requested changes
Try to keep each line less than 80 chars long. 80 is a soft limit while the hard limit is 100 chars.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +        cin >> k;
Also check that `K <= N`.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +    O(N*K) due to memoization (due to the 'cache' variable), and O(N) stack space (due to recursion)
Space complexity is just `O(N * K)`. Also, there's no need to mention the reason here.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +    O(N*K) - cache[i][j] will be computed at most once for each i<=N and j<=K
There's no need to mention the reason here.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +int BinomialCoefficientHelper(int N, int K, vector<vector<int> > cache)//uses recurrence relation and fills cache to find binomial coefficient of N & K
Pass `cache` by reference to prevent creating copies of it during each recursive call.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +    vector< vector<int> > cache;//2d cache vector will be used to memoize BinomialCoefficient values between calls
Please remove the spaces between `<` and `vector` and the two `>`s. C++11 and later versions can differentiate between the operator `>>` and nested angle brackets for template parameters.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +    for(int i = 0; i < (N + 1); i++)//cache[i][j] is initialized to FLAG value (-1) at start
Change `i < (N + 1)` to `i <= N` for simplicity.

2017-06-09 02:36 UTC, faheel commented on NumberTheory/BinomialCoefficient.cpp
> +    int out;//will contain the value to be returned
Rename `out` to `result`, as that would be a better name for the variable.

2017-06-09 03:51 UTC, eskeype commented
Thanks for checking out my code! I will make all the updates that you suggested, but I want to hear your thoughts on having BinomialCoefficients(N, K) return 0 when N < K

2017-06-09 04:02 UTC, eskeype commented
Ok, committed the changes you suggested. A few of my lines went over 80 characters (2 or 3 lines), and I added the functionality that BinomialCoefficients(N,K) = 0 when N<K instead of updating the testing function. If you disagree I can change the function appropriately.

2017-06-10 05:32 UTC, faheel commented
@eskeype Yes, C(n, K) = 0, for n < k.

2017-06-10 05:53 UTC, faheel commented
@eskeype Can you also add the test for this? It will be similar to the one for Fibonacci, which can be found [here](https://github.com/faheel/Algos/blob/master/Test/NumberTheory/Fibonacci.test.cpp).

2017-06-10 15:07 UTC, eskeype commented
Ok I'll do that. Should I add the overflow test as well? If so, do you think I should have the function take and return signed integers? Or should I switch to unsigned or unsigned long?

2017-06-10 15:56 UTC, faheel commented
You can use `unsigned long long` (which is 64-bit unsigned integer) as that would increase the range to 18446744073709551615, from the current range of 2147483647.

2017-06-10 18:29 UTC, eskeype commented
Ok absolutely. I will have BinomialCoefficients take 'int' inputs and return ULL outputs.

2017-06-10 22:04 UTC, eskeype commented
Ok, I made the suggested changes, and I added in some test cases. I calculated the test values using a python library function for binomial coefficients.

For the overflow tests, I found inputs with output values greater than 2^64, and I tested to see if the the outputs were equal to python's outputs modulo 2^64 (which I hardcoded into the testing file)

2017-06-10 22:09 UTC, eskeype commented
By the way, I noticed that Fibonacci.test.cpp wouldn't compile on my machine. I believe that this can be fixed by adding '#define TEST' to Fibonacci.test.cpp.

2017-06-10 23:44 UTC, faheel commented
Thanks for pointing out the missing `#define TEST` for Fibonacci.test.cpp.

2017-06-10 23:50 UTC, merged

2017-06-10 23:54 UTC, faheel commented
@eskeype Thanks for your time and contribution on this :smiley:! And congratulations on your first PR merge :tada:

2017-06-11 02:52 UTC, eskeype commented
Thanks for all of the guidance!