Add dijkstra algorithm
ProAlgos/ProAlgos-Cpp pull request #78
Opened 2017-07-06 19:22 UTC by kapildeshpande

2017-07-19 12:45 UTC, faheel commented
There have been lots of suggestions recently by interested contributors to add more algorithms and data structures to the project, which I have currently put on hold because I want to close issue #74 first, as it would require a complete reorganisation of files and some refactoring of code.

I previously thought that I would work on #74 once the currently active PRs are merged, but I feel that it would take much longer that way. So, if it's not too inconvenient for you, I would like to work on issue #74 as soon as possible. The remaining work on this PR (and others) can be carried on afterwards. Once the project is refactored, all you would need to do is `git fetch upstream` and move the code that you wrote to the new appropriate directory.

So, what do you say?

2017-07-19 13:29 UTC, kapildeshpande commented
Ok no problem.

On 19-Jul-2017 6:15 PM, "Faheel Ahmad" <notifications@github.com> wrote:

> There have been lots of suggestions recently by interested contributors to
> add more algorithms and data structures to the project, which I have
> currently put on hold because I want to close issue #74
> <https://github.com/faheel/Algos/issues/74> first, as it would require a
> complete reorganisation of files and some refactoring of code.
>
> I previously thought that I would work on #74
> <https://github.com/faheel/Algos/issues/74> once the currently active PRs
> are merged, but I feel that it would take much longer that way. So, if it's
> not too inconvenient for you, I would like to work on issue #74
> <https://github.com/faheel/Algos/issues/74> as soon as possible. The
> remaining work on this PR (and others) can be carried on afterwards. Once
> the project is refactored, all you would need to do is git fetch upstream
> and move the code that you wrote to the new appropriate directory.
>
> So, what do you say?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faheel/Algos/pull/78#issuecomment-316374193>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIMzoJ-zERR8UdMYm5uBey6H_L5rG4Bdks5sPfpkgaJpZM4OQEoO>
> .
>

2017-08-23 21:16 UTC, faheel requested changes
Thanks for adding Dijkstra's algorithm; it has been long overdue :sweat_smile:. It would be great if you could also add unit tests for it with a few test cases. The details for it can be found in [UNIT_TESTS.md](https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md).

Also, please rename the file to just `dijkstra.cpp` and its parent directory to `graph`.

2017-08-23 21:16 UTC, faheel commented on C++/source/Graph algorithms/Dijkstra_algorithm.cpp
> +int dist[MAX];
Please make these containers local to `main()` and pass them by reference to whichever functions need them.

Also, you can declare `visited` and `dist` as `vector<bool>` and `vector<int>` respectively, which would remove the need for using the constant `MAX`.

2017-08-23 21:16 UTC, faheel commented on C++/source/Graph algorithms/Dijkstra_algorithm.cpp
> +	int no_of_vertex,no_of_edges,source;
Use `num_` instead of `no_of_`, since it is a more widely used convention.

2017-08-30 12:39 UTC, kapildeshpande commented
Ok no problem

On 24-Aug-2017 2:46 AM, "Faheel Ahmad" <notifications@github.com> wrote:

> *@faheel* requested changes on this pull request.
>
> Thanks for adding Dijkstra's algorithm; it has been long overdue 😅. It
> would be great if you could also add unit tests for it with a few test
> cases. The details for it can be found in UNIT_TESTS.md
> <https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md>.
> ------------------------------
>
> In C++/source/Graph algorithms/Dijkstra_algorithm.cpp
> <https://github.com/faheel/Algos/pull/78#discussion_r134867663>:
>
> > +	O(n^2)
> +
> +*/
> +
> +#include<iostream>
> +#include<utility>
> +#include<vector>
> +#include<set>
> +#include<climits>
> +using namespace std;
> +
> +#define MAX 10001
> +
> +vector < pair <int,int> > adj[MAX];
> +bool visited[MAX];
> +int dist[MAX];
>
> Please make these containers local to main() and pass them by reference
> to whichever functions need them.
>
> Also, you can declare visited and dist as vector<bool> and vector<int>
> respectively, which would remove the need for using the constant MAX.
> ------------------------------
>
> In C++/source/Graph algorithms/Dijkstra_algorithm.cpp
> <https://github.com/faheel/Algos/pull/78#discussion_r134869005>:
>
> > +		if (visited[x])
> +			continue;
> +		visited[x] = 1;
> +		for (int i=0;i<adj[x].size();i++) {
> +			int y = adj[x][i].first;
> +			if (dist[x] + y < dist[adj[x][i].second]) {
> +				dist[adj[x][i].second] = dist[x] + y;
> +				s.insert(make_pair(dist[adj[x][i].second],adj[x][i].second));
> +			}
> +		}
> +
> +	}
> +}
> +
> +int main () {
> +	int no_of_vertex,no_of_edges,source;
>
> Use num_ instead of no_of_, since it is a more widely used convention.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faheel/Algos/pull/78#pullrequestreview-58212007>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIMzoHuDTwdANHMETr2AEqfGgkM6mh24ks5sbJa5gaJpZM4OQEoO>
> .
>

2018-01-10 18:09 UTC, faheel commented
Closing this due to lack of activity for a long time.

2018-01-10 18:09 UTC, closed without merging