Added time and space complexity to N-Queens problem
ProAlgos/ProAlgos-Cpp pull request #81
Opened 2017-07-08 11:38 UTC by janos-laszlo

Hello, I have added the time and space complexity to the N-Queens problem.

P.S.:This is my first contribution, sorry if I haven't done something right.

2017-07-08 11:52 UTC, faheel requested changes
Underline the "headings" by dashes (`-`) and remove the trailing `:`

2017-07-08 18:32 UTC, janos-laszlo commented
Hope this is what you asked :)

2017-07-09 02:22 UTC, faheel approved these changes

2017-07-09 02:23 UTC, merged

2017-07-09 02:24 UTC, faheel commented
Thanks for helping out! 😀