Added required description comment in binary_search.cpp
ProAlgos/ProAlgos-Cpp pull request #9
Opened 2017-01-31 11:34 UTC by varshika03

Review it so that I can add more.

2017-01-31 12:36 UTC, quantum-pie commented
I think space complexity is O(1) because you don't need additional memory

2017-01-31 13:22 UTC, faheel requested changes
Remove all the angle brackets (`<` & `>`). They are used in the format just for showing that the enclosing text is a description of the text, and not the actual text.

2017-01-31 13:22 UTC, faheel commented on Searching/BinarySearch.cpp
> +    O(logn), where <n is the number of elements in the array>
I suggest writing `O(logn)` as either `O(logN)`, `O(log(n))` or `O(log(N))` for more clarity.

`O(log(N))` would be the best way IMO.

2017-01-31 13:25 UTC, faheel commented on Searching/BinarySearch.cpp
> +    O(n), where <n is the number of elements in the array>
It's actually `O(1)` as only a constant amount of **extra memory** is required.

2017-01-31 13:26 UTC, faheel requested changes

2017-01-31 13:26 UTC, faheel commented on Searching/BinarySearch.cpp
> +    O(n), where <n is the number of elements in the array>
It's actually `O(1)` as only a constant amount of **extra memory** is required.

2017-02-01 02:31 UTC, faheel requested changes
Newlines please! As in this:
```C++
/*
    <Name of algorithm>:
    <Brief description>

    Time complexity:
    O(...), where <description of variable(s)>    
    
    Space complexity:
    O(...), where <description of variable(s)>
*/
```

And again, I suggest writing `O(logn)` as either `O(logN)`, `O(log(n))` or `O(log(N))` for more clarity.
I think `O(log(N))` would be the best way.

2017-03-12 10:43 UTC, faheel commented
Closing this since there hasn't been any activity for a long time.

2017-03-12 10:43 UTC, closed without merging