Priority Queue
ProAlgos/ProAlgos-Cpp pull request #92
Opened 2017-07-24 20:41 UTC by Kuldip397

Priority Queue using heap data structure added in C++/test/data_structures directory under #91 issue.

2017-07-25 00:46 UTC, faheel requested changes
@Kuldip397 Thank you for contributing! There are a few things I would like to point out:
- A data structure should be implemented as a `class` so that it can be used in a way similar to STL containers. Eg. usage in an external program:
```C++
#include "data_structures/priority_queue.hpp"

...

PriorityQueue pq;
pq.insert(10);
pq.insert(5);
pq.insert(15);

while (!pq.is_empty()) {
    cout << pq.max();
    pq.remove();
}

...
```
- Mention it in the program whether the priority will be highest for the largest value or the smallest value.

- The code should be placed under the `include` directory, not `test`. The class should be declared in `priority_queue.hpp` and its implementation should be in `priority_queue.cpp` (both under `include/data_structures/`). The unit tests should be defined in `test/data_structures/priority_queue.test.cpp`.

2017-07-25 13:27 UTC, Kuldip397 commented
Thanks for your review. I'll make the changes as according to your suggestions.
Can you please make me clear, what I'm supposed to do with unit tests which is going to be defined in test/data_structures/priority_queue.test.cpp.

2017-07-26 04:44 UTC, faheel commented
In the unit test, you can insert and remove elements from the priority queue and after a few insertions and removals check that the `max()` returns the value that's expected. You can have 3-4 test cases with different values being inserted and removed, in each of which you should check that the `max()` returns the correct value 5 or more times. Also, check for edge cases like inserting the same value, or removing a value that's not present etc.

To know what changes you would need to do to add the unit test, read [Adding unit tests for C++ code](https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md).

2017-07-30 16:11 UTC, faheel requested changes
- In all the filenames, `PriorityQueue` should be changed to `priority_queue` (only the filenames; the class remains as it is)
- Please don't start a function with a blank line.
- All function parameters whose value isn't changed should be accepted as a constant reference `const type& param` instead of `type param` to prevent creating multiple copies of them.
- Use `and` and `or` instead of `&&` and `||`
- Make sure that each level of indentation is four spaces. You can convert all tabs to spaces using your text editor.

2017-07-30 16:11 UTC, faheel commented on C++/test/data_structures/PriorityQueue.test.cpp
> +#include "../../include/data_structures/PriorityQueue.cpp"
You can remove the prefix `../../include/` from the include path as the `include` directly is already added to the include path in the Makefile.

2017-07-30 16:11 UTC, faheel commented on C++/test/data_structures/PriorityQueue.test.cpp
> +TEST_CASE("Checking max() and remove() functions return the expected value", "[PriorityQueue]"){
Change all the `[PriorityQueue]` tags to `[priority_queue]`.

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.cpp
> +    O(1) - for max() , constant amount of time
The time and space complexity for `insert()`, `remove()` and `max()` should be removed from here and should instead be mentioned in the description comment of the respective function. See [this file](https://github.com/faheel/Algos/blob/master/C%2B%2B/include/data_structures/disjoint_set.cpp) for an example.

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.cpp
> +#include <stdlib.h>
`stdlib.h` -> `cstdlib`

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.cpp
> +	   Variable "position" represent the position at which the heap property is violated */
The description of each member function should be mentioned in its description comment (along with the time and space complexity, if it's an algorithmic function). See [this file](https://github.com/faheel/Algos/blob/master/C%2B%2B/include/data_structures/disjoint_set.cpp) for an example.

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.cpp
> +	while(2*position <= static_cast<int>(v.size())-1) { // static_case<int> used to typecaste v.size() to return signed int value
The comment can be removed as it doesn't add any useful meaning.

2017-07-30 16:11 UTC, faheel commented on C++/test/data_structures/PriorityQueue.test.cpp
> +	PriorityQueue pq; // creating PriorityQueue class object
The comment can be removed as it doesn't give any extra meaning.

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.cpp
> +		position = position/2;
- The parenthesis inside `[]` can be removed
- Add a space to the left and right of `/`

2017-07-30 16:11 UTC, faheel commented on C++/include/data_structures/PriorityQueue.hpp
> +	std::vector<int> v;
Give `v` a more meaningful name, such as `values` or `priorities`.

2018-01-10 18:33 UTC, faheel approved these changes

2018-01-10 18:33 UTC, faheel commented
@Kuldip397 Please merge your branch with upstream and then it'll be good to merge 👍

2018-08-30 14:49 UTC, alxmjo commented
Closing due to inactivity.

2018-08-30 14:49 UTC, closed without merging